### ISSUE TITLE
gulp main task fail at Windows.

### ISSUE THREAD

**Issue by gintsgints** [antonybudianto/angular2-starter#60] opened 2016-04-10 06:19 UTC
## Issue Overview
First build after clone gives error: "A project cannot be used in two compilations at the same time. Create multiple projects with createProject instead"

## Issue Description
After clone I issued:
```
npm install
bower install
```

Next command:
```
gulp
```
Gives me error: 
Compiling C:\Users\gpolis\Documents\work\ang2\angular2-starter\app\app.component.ts...
C:\Users\gpolis\Documents\work\ang2\angular2-starter\node_modules\gulp-typescript\release\main.js:71
            throw new Error('gulp-typescript: A project cannot be used in two compilations at the same time. Create multiple projects with createProject instead.');
            ^

Error: gulp-typescript: A project cannot be used in two compilations at the same time. Create multiple projects with createProject instead.
    at compile (C:\Users\gpolis\Documents\work\ang2\angular2-starter\node_modules\gulp-typescript\release\main.js:71:19)

## Reproducables
git clone
npm install
bower install
gulp

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows 	|
| **Node version**     	| 4.x   	|
| **NPM Version**      	| 3.x    	|
| **Environment**       | Browser         |

**Comment by antonybudianto** [comment] 2016-04-10 06:56
I think this is the plugin [issue](https://github.com/ivogabe/gulp-typescript/issues/241)

**Comment by antonybudianto** [comment] 2016-04-10 07:01
I can't reproduce the issue, can you also post the issue to the plugin repo? 
Thanks

**Comment by gintsgints** [comment] 2016-04-10 07:58
Ok. Will do.

**Comment by gintsgints** [comment] 2016-04-10 08:05
Related issue - https://github.com/ivogabe/gulp-typescript/issues/322

**Comment by antonybudianto** [comment] 2016-04-10 09:03
Nice, you should post the `typescript.js` in `tasks` too

**Comment by gintsgints** [comment] 2016-04-10 14:02
Probably you get this message with latest gulp-typescript?

As stated at they message, you need to create own project for each compilation task.

**Comment by antonybudianto** [comment] 2016-04-10 14:14
i see, but i didn't think one would call those tasks at the same time though, then
I will refactor the compile tasks soon, for the moment, you can move the `createProject` statement into each task as they said

**Comment by gintsgints** [comment] 2016-04-10 14:16
Check my pull request. Worked for me.

**Comment by antonybudianto** [comment] 2016-04-10 14:17
that was fast! thank you

**Comment by antonybudianto** [comment] 2016-04-10 14:21
Merged! 
Thank you @gintsgints for PR! :+1:

**Closed** 2016-04-10 14:20 UTC
