### ISSUE TITLE
Test succeed but the report is not generated

### ISSUE THREAD

**Issue by pgarge** [antonybudianto/angular2-starter#97] opened 2016-06-09 17:22 UTC
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 1 of 1 SUCCESS (0 secs / 0.567 secs)
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 1 of 1 SUCCESS (1.136 secs / 0.567 s
ERROR: 'EXCEPTION: Error in :0:0'
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 1 of 1 SUCCESS (1.136 secs / 0.567 s
ERROR: 'STACKTRACE:'
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 1 of 1 SUCCESS (1.136 secs / 0.567 s
ecs)
Test Done with exit code: 0
Remapping coverage to TypeScript format...
[11:46:55] Finished 'unit-test' after 7.37 s
[11:46:55] Starting 'test'...
[11:46:55] Finished 'test' after 15 µs
Remapping done! View the result in report/remap/html-report
**09 06 2016 11:47:05.379:WARN [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Disconnected (
PhantomJS 2.1.1 (Windows 7 0.0.0): Executed 1 of 1 DISCONNECTED (11.144 secs / 0
.567 secs)
Test Done with exit code: 1
Remapping coverage to TypeScript format...
[11:47:05] 'unit-test' errored after 17 s
[11:47:05] Error: Unit test failed.
    at formatError (C:\Users\pgarge\AppData\Roaming\npm\node_modules\gulp\bin\gu
lp.js:169:10)**
    at Gulp.<anonymous> (C:\Users\pgarge\AppData\Roaming\npm\node_modules\gulp\b
in\gulp.js:195:15)
    at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\acex\16.09\AppLib\CE.InsightsWeb\node
_modules\orchestrator\index.js:264:8)
    at C:\acex\16.09\AppLib\CE.InsightsWeb\node_modules\orchestrator\index.js:27
5:23
    at finish (C:\acex\16.09\AppLib\CE.InsightsWeb\node_modules\orchestrator\lib
\runTask.js:21:8)
    at cb (C:\acex\16.09\AppLib\CE.InsightsWeb\node_modules\orchestrator\lib\run
Task.js:29:3)
    at karmaDone (C:\acex\16.09\AppLib\CE.InsightsWeb\tasks\test.js:23:13)
    at removeAllListeners (C:\acex\16.09\AppLib\CE.InsightsWeb\node_modules\karm
a\lib\server.js:336:7)
    at C:\acex\16.09\AppLib\CE.InsightsWeb\node_modules\karma\lib\server.js:347:
9
    at Server.<anonymous> (net.js:1503:9)
    at Server.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1549:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Remapping done! View the result in report/remap/html-report

Any help will be appreciated.

**Comment by antonybudianto** [comment] 2016-06-10 00:56
Do you use the latest angular2-starter? 
Sorry I can't reproduce it

**Comment by antonybudianto** [comment] 2016-06-13 14:49
closing because no repro steps

**Closed by antonybudianto** 2016-06-13 14:49 UTC
Labels: need repro

**Comment by dmitripotapov** [comment] 2017-01-03 10:26
Hello,
I have same issue, could you help me.

`03 01 2017 12:21:47.429:INFO [karma]: Karma v1.3.0 server started at http://localhost:9876/
03 01 2017 12:21:47.432:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
03 01 2017 12:21:47.440:INFO [launcher]: Starting browser PhantomJS
03 01 2017 12:21:49.191:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on socket /#7JkPqiVw1ljjQoBQAAAA with id 52982360
03 01 2017 12:21:59.204:WARN [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  Disconnected, because no message in 10000 ms.


[12:21:59] Remapping coverage to TypeScript format...
[12:21:59] Test Done with exit code: 1
[12:21:59] 'unit-test' errored after 21 s
[12:21:59] Error: 1
    at formatError (C:\Users\38304252230\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\formatError.js:20:10)
    at Gulp.<anonymous> (C:\Users\38304252230\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\log\events.js:41:15)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\38304252230\smit_workspace\kais-ui\node_modules\orchestrator\index.js:264:8)
    at C:\Users\38304252230\smit_workspace\kais-ui\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\38304252230\smit_workspace\kais-ui\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (C:\Users\38304252230\smit_workspace\kais-ui\node_modules\orchestrator\lib\runTask.js:29:3)
    at DestroyableTransform.<anonymous> (C:\Users\38304252230\smit_workspace\kais-ui\config\gulp\tasks\test.js:67:13)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at finishMaybe (C:\Users\38304252230\smit_workspace\kais-ui\node_modules\remap-istanbul\node_modules\readable-stream\lib\_stream_writable.js:475:14)
    at endWritable (C:\Users\38304252230\smit_workspace\kais-ui\node_modules\remap-istanbul\node_modules\readable-stream\lib\_stream_writable.js:485:3)
    at DestroyableTransform.Writable.end (C:\Users\38304252230\smit_workspace\kais-ui\node_modules\remap-istanbul\node_modules\readable-stream\lib\_stream_writable.js:455:41)
    at DestroyableTransform.onend (C:\Users\38304252230\smit_workspace\kais-ui\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:291:16)
[12:21:59] Remapping done! View the result in report/remap/html-report
`

package.json

`"@angular/common": "~2.4.0",
    "@angular/compiler": "~2.4.0",
    "@angular/core": "~2.4.0",
    "@angular/forms": "~2.4.0",
    "@angular/http": "~2.4.0",
    "@angular/platform-browser": "~2.4.0",
    "@angular/platform-browser-dynamic": "~2.4.0",
    "@angular/router": "~3.4.0",
    "@ngstarter/systemjs-extension": "1.0.0-rc.4",
    "@types/core-js": "^0.9.34",
    "@types/jasmine": "^2.5.36",
    "@types/lodash": "^4.14.37",
    "@types/selenium-webdriver": "^2.44.28",
    "bootstrap": "^3.3.6",
    "bootstrap-sass": "^3.3.7",
    "codelyzer": "1.0.0-beta.3",
    "core-js": "^2.4.1",
    "del": "~2.2.2",
    "express": "^4.13.4",
    "font-awesome": "^4.7.0",
    "glob": "^7.0.6",
    "gulp": "^3.9.1",
    "gulp-cssnano": "^2.1.2",
    "gulp-flatten": "^0.3.1",
    "gulp-if": "~2.0.1",
    "gulp-protractor": "^3.0.0",
    "gulp-rev": "^7.1.2",
    "gulp-rev-replace": "^0.4.3",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^2.2.0",
    "gulp-template": "^4.0.0",
    "gulp-tslint": "6.1.2",
    "gulp-typescript": "~3.1.2",
    "gulp-uglify": "~2.0.0",
    "gulp-useref": "~3.1.2",
    "jasmine-core": "~2.5.0",
    "jquery": "^3.1.0",
    "karma": "~1.3.0",
    "karma-coverage": "~1.1.1",
    "karma-ie-launcher": "^1.0.0",
    "karma-intl-shim": "^1.0.3",
    "karma-jasmine": "~1.0.2",
    "karma-phantomjs-launcher": "~1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "lodash": "^4.15.0",
    "moment": "^2.17.1",
    "ng2-modal": "0.0.21",
    "ng2-pagination": "^0.3.5",
    "ng2-tabs": "0.0.6",
    "ng2-tooltip": "0.0.4",
    "ng2-translate": "^4.2.0",
    "phantomjs-prebuilt": "^2.1.12",
    "remap-istanbul": "~0.6.4",
    "require-dir": "~0.3.0",
    "run-sequence": "~1.2.2",
    "rxjs": "^5.0.1",
    "systemjs": "^0.19.40",
    "tslint": "~3.15.1",
    "typescript": "~2.0.6",
    "yargs": "^6.3.0",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "browser-sync": "^2.17.5",
    "connect-history-api-fallback": "^1.2.0",
    "ts-node": "^1.6.1"
  }`
