### ISSUE TITLE
Can`t make breakpoints using debugger in unit test

### ISSUE THREAD

**Issue by darxx** [antonybudianto/angular2-starter#101] opened 2016-06-14 14:54 UTC
In chrome browser on port 9876 on break point to analyze code.
## Issue Overview
http://prntscr.com/bga96j

## Issue Description
add debugger in tests

## Reproducables
just try to add debugger in tests and run chrome browser on localhost:9876

## Information
|                      	|                                 	|
|---------------------	|---------------------------------	|
| **Operating System** 	| Windows/OSX/Ubuntu/orYourOSHere 	|
| **Node version**     	| 4.x/5.x/orYourNodeVersionHere   	|
| **NPM Version**      	| 2.x/3.x/orYourNPMVersionHere    	|
| **Environment**       | Browser/Mobile/WebWorker          |

**Comment by antonybudianto** [comment] 2016-06-14 15:07
not sure how to fix this, [this](http://bahmutov.calepin.co/debugging-karma-unit-tests.html) may help

**Comment by darxx** [comment] 2016-06-14 15:55
Tomorrow I will try to run separately. I hope this helps.

**Comment by darxx** [comment] 2016-06-15 05:42
This information was not very helpful. I guess this problems is related to type script remapping .

**Comment by antonybudianto7** [comment] 2016-06-15 05:45
Remapping is a separate process after karma's done, not sure why it's the problem.

**Comment by antonybudianto7** [comment] 2016-06-15 06:03
Anyway I need more details on how you do the debugging.
For now, I just tried `gulp test -w` and use Karma Chrome launcher, then do click **DEBUG**, and then I started to put `debugger;` statement in spec file, and refresh the debug page, here is what I got
![test](https://cloud.githubusercontent.com/assets/14085717/16069525/56ce73b2-32f9-11e6-8b7d-54a8d44fe417.png)

It worked well (although I got tslint warning on `debugger;` usage)

**Comment by darxx** [comment] 2016-06-15 06:13
This works as expected. Working on "real time" debugging and compiling. 
Created 
gulpfile.js
gulp.task('serv', function() {
	runSequence('serve-local', 'unit-test');
});

and
serve.js
    gulp.task('serve-local', function ()
    {
        startBrowsersync(config.browserSync.dev);
    });

Then added debugger after launched 
gulp serv --exclude-source -w

I guess  ['tsc-app', 'watch-ts'] need to be added.

**Comment by antonybudianto7** [comment] 2016-06-15 06:15
closing this issue then

**Comment by darxx** [comment] 2016-06-15 06:15
{ included: false, watched: false, pattern: 'src/app/**/*.ts' },
In Karma why included: false is false?

**Closed by antonybudianto7** 2016-06-15 06:15 UTC

**Comment by antonybudianto7** [comment] 2016-06-15 06:17
because ts files are not loaded directly via script tag
https://karma-runner.github.io/0.13/config/files.html

**Comment by darxx** [comment] 2016-06-15 11:33
After changing spec file need to kill gulp test -w and run over again.

**Comment by antonybudianto7** [comment] 2016-06-15 11:37
Sorry please explain the detail more, why you need to kill the test watch?
Working well on my side.

**Comment by darxx** [comment] 2016-06-16 06:42
Can You Explain local development cycle writing code, test and checking changes on web server? Because every time I need to close gulp commands and start others tasks to preprocess type script and code coverage and start static server.

**Comment by darxx** [comment] 2016-06-16 06:44
And using  --exclude-source on every gulp command to avoid writing directly to c drive is not best solution. Currently local workflow is main issue.

**Comment by antonybudianto7** [comment] 2016-06-16 07:03
If the problem is workflow, then it'll get nowhere, since everyone have different opinions on this. You can fork the starter and start implementing your desired flows, I'll help where I can.
